#!/bin/sh -e

case "$1" in
    configure|reconfigure)
        mkdir -p /etc/adguardhome
        mkdir -p /var/adguardhome
        mkdir -p /var/log/adguardhome

        ucf /usr/share/adguardhome/configuration /etc/adguardhome/AdGuardHome.yaml
        ucfr adguardhome /etc/adguardhome/AdGuardHome.yaml

        systemctl daemon-reload
        systemctl enable adguardhome
        systemctl restart adguardhome
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
