#!/bin/sh -e

case "$1" in
    remove)
        systemctl daemon-reload
    ;;

    purge)
        rm -rf /var/adguardhome
        rm -rf /var/log/adguardhome
        rm -rf /etc/adguardhome/AdGuardHome.yaml
        if which ucf >/dev/null; then
            ucf --purge /etc/adguardhome/AdGuardHome.yaml
        fi
    ;;

    disappear|upgrade|failed-upgrade|abort-install|abort-upgrade)
    ;;

    *) echo "$0: didn't understand being called with \`$1'" 1>&2
    ;;
esac

exit 0
